[WIP]チャット画面の実装
katotakumi/chat-space pull request #3
Opened 2019-03-28 08:13 UTC by katotakumi

# WHAT
チャット画面を実装する

# WHY
サービスに必須の機能であるため

2019-03-28 08:14 UTC, hiroki5123 commented
実際の画面のキャプチャをこちらに添付してください。

2019-03-28 08:24 UTC, ghost requested changes
参考程度に見本を見るくらいならいいと思いますが、がっつりクラス名も一緒でCSSもそのまま写しているようでは、全く力がつかないと思います。

また、エンジニアとしての力をつけることを目的にしなければならないのに、これを見る限りChatSpaceを早く終わらせることが目的になっているように見えます。

ご自分でよく考えながら、わからないところは質問しながら実装していただければと思います。

2019-03-28 08:24 UTC, ghost commented on app/views/massages/index.html.haml
> +        %input{:name => "authenticity_token", :type => "hidden", :value => "0GnUC0T/bM+NvZpJSFcqmlntzgPR/0nkhIR6UIQu6KgJ0xVRR1Qe65nGcj1SgxT77JRKExL9P8kuUXI/n0RqOA=="}/
これはなんですか？

2019-03-28 08:24 UTC, ghost commented on app/assets/stylesheets/application.scss
> +    /*TODO formのレイアウトが崩れている、スクロールした時に固定できていない*/
これは修正してありますでしょうか？

2019-03-28 08:24 UTC, hiroki5123 commented on app/assets/stylesheets/_variable.scss
> +body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, code, form, fieldset, legend, input, textarea, p, blockquote, th, td {
なんでこれ書いてるんですか？
_reset.scssの方に書いてありますよ

2019-03-28 08:24 UTC, ghost commented on app/assets/stylesheets/application.scss
> +.flash-box{
ここ以下は全て別のファイルに書いてそのファイルをimportしてください。

2019-03-28 08:24 UTC, ghost commented on app/assets/stylesheets/application.scss
> +    display: flex;
インデントずれています。

2019-03-28 08:24 UTC, ghost commented on app/assets/stylesheets/application.scss
> +    .main-header__left-box{
ここもそうですが他のところもアンパサンド使ってください。

2019-03-28 08:24 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +    / = render partial: 'layouts/flash'
このファイルは作ってあるんですか？
なんで作ってないファイルを指定しているんでしょうか・・・・

2019-03-28 08:24 UTC, hiroki5123 commented on app/views/massages/index.html.haml
> +            %a{:href => "/groups/new"}
aタグは全てlink_toに置き換えてください。

2019-03-28 08:32 UTC, katotakumi commented on app/assets/stylesheets/application.scss
> +.flash-box{
別ファイルに分けました。

2019-03-28 08:33 UTC, katotakumi commented on app/assets/stylesheets/_variable.scss
> +body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, code, form, fieldset, legend, input, textarea, p, blockquote, th, td {
該当部分を削除しました。

2019-03-28 08:33 UTC, katotakumi commented on app/assets/stylesheets/application.scss
> +    /*TODO formのレイアウトが崩れている、スクロールした時に固定できていない*/
コメント削除して修正しました。

2019-03-28 08:35 UTC, katotakumi commented on app/views/layouts/application.html.haml
> +    / = render partial: 'layouts/flash'
該当部分を削除しました。

2019-03-28 08:53 UTC, katotakumi commented on app/views/massages/index.html.haml
> +        %input{:name => "authenticity_token", :type => "hidden", :value => "0GnUC0T/bM+NvZpJSFcqmlntzgPR/0nkhIR6UIQu6KgJ0xVRR1Qe65nGcj1SgxT77JRKExL9P8kuUXI/n0RqOA=="}/
不要だったので、削除しました。

2019-03-28 09:10 UTC, katotakumi commented on app/assets/stylesheets/application.scss
> +    display: flex;
インデント直しました。

2019-03-29 07:52 UTC, katotakumi commented on app/assets/stylesheets/application.scss
> +    .main-header__left-box{
アンパサンドを使用して修正しました。

2019-03-29 09:42 UTC, katotakumi commented on app/views/massages/index.html.haml
> +            %a{:href => "/groups/new"}
link_toに置き換えました。

2019-03-29 09:53 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-03-29 09:53 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +!!!
mailerファイル使用しないので消しましょう

2019-03-29 09:53 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> +
こちらも

2019-03-29 10:03 UTC, katotakumi commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しました。

2019-03-29 10:07 UTC, TOMARUMARU approved these changes
LGTM

2019-03-29 10:33 UTC, merged